#   - Ubuntu 24.04
#   - ROS2 Jazzy

services:
  ros2cont:
    tty: true 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: FRDualArm    # identifier
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=$DISPLAY
volumes: 
  ros2cont: