# Docker compose file for initializing ROBO.666 environment
# 
#   - Ubuntu 24.04 Jammy 
#   - ROS2 Jazzy 
#   ROBO.400 docker setup edited for ROBO.666
#

services:
  ros2cont:
    tty: true 
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: robo666    # identifier
    volumes:
      - ./ros2env/src:/up/ros2env/src      # bind the directories 
      - /tmp/.X11-unix:/tmp/.X11-unix:rw   # enable cv2 tools 
  #  devices:   # remove comments for adding web cameras, see instructions in README.md   
  #    - /dev/video0:/dev/video0
  #    - /dev/video0:/dev/video1
  #    - /dev/video0:/dev/video2
  #    - /dev/video0:/dev/video3
    environment:
      - DISPLAY=$DISPLAY    # env. variable for display
volumes: 
  ros2cont: